# Generated by Django 5.2.9 on 2026-05-29 16:43

import django.db.models.deletion
import netbox.models.deletion
import netbox_c3nav.utils
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0216_latitude_longitude_validators'),
        ('extras', '0133_make_cf_minmax_decimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('level_id', models.PositiveIntegerField()),
                ('level_index', models.CharField(max_length=20)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dcim.device')),
            ],
            options={
                'verbose_name': 'Device Position',
                'verbose_name_plural': 'Device Positions',
                'ordering': ('id',),
                'default_related_name': 'c3nav_position',
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Overlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to=netbox_c3nav.utils.file_upload_path)),
                ('external_url', models.URLField(blank=True, max_length=255)),
                ('bottom', models.DecimalField(decimal_places=2, max_digits=6)),
                ('left', models.DecimalField(decimal_places=2, max_digits=6)),
                ('top', models.DecimalField(decimal_places=2, max_digits=6)),
                ('right', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comments', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Overlay',
                'verbose_name_plural': 'Overlays',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
