# Generated by Django 5.2.9 on 2026-06-30 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_c3nav', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overlay',
            options={'ordering': ('level_index', 'name')},
        ),
        migrations.AddField(
            model_name='overlay',
            name='is_background',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='overlay',
            name='opacity',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='overlay',
            name='zindex',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='overlay',
            constraint=models.CheckConstraint(condition=models.Q(('opacity__isnull', True), models.Q(('opacity__gte', 0.0), ('opacity__lte', 1.0)), _connector='OR'), name='opacity-limits', violation_error_message='Opacity must be between 0 and 1 or null'),
        ),
    ]
