# Generated by Django 5.2.9 on 2026-07-02 18:05

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.fields
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0216_latitude_longitude_validators'),
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_c3nav', '0002_alter_overlay_add_is_background_opacity_and_zindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkerStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(max_length=100)),
                ('icon_size', models.PositiveIntegerField(blank=True, null=True)),
                ('icon_rotation', models.FloatField(blank=True, null=True)),
                ('icon_is_rotating', models.BooleanField(blank=True, null=True)),
                ('icon_color', utilities.fields.ColorField(blank=True, max_length=6, null=True)),
                ('marker_style', models.CharField(blank=True, max_length=32, null=True)),
                ('marker_size', models.PositiveIntegerField(blank=True, null=True)),
                ('marker_color', utilities.fields.ColorField(blank=True, max_length=6, null=True)),
                ('add_background', models.BooleanField(blank=True, null=True)),
                ('background_color', utilities.fields.ColorField(blank=True, max_length=6, null=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'MarkerStyle',
                'verbose_name_plural': 'MarkerStyles',
                'ordering': ('name',),
                'default_related_name': 'marker_style',
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MarkerStyleBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('device_role', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dcim.devicerole')),
                ('device_type', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dcim.devicetype')),
                ('marker_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marker_style_bindings', to='netbox_c3nav.markerstyle')),
            ],
            options={
                'verbose_name': 'Marker Style Binding',
                'verbose_name_plural': 'Marker Style Bindings',
                'default_related_name': 'marker_style_binding',
            },
        ),
        migrations.AddField(
            model_name='markerstyle',
            name='device_roles',
            field=models.ManyToManyField(through='netbox_c3nav.MarkerStyleBinding', to='dcim.devicerole'),
        ),
        migrations.AddField(
            model_name='markerstyle',
            name='device_types',
            field=models.ManyToManyField(through='netbox_c3nav.MarkerStyleBinding', to='dcim.devicetype'),
        ),
        migrations.AddConstraint(
            model_name='markerstylebinding',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('device_role__isnull', False), ('device_type__isnull', True)), models.Q(('device_role__isnull', True), ('device_type__isnull', False)), _connector='OR'), name='device-role-or-type', violation_error_message='Binding can either be for a device role or a device type'),
        ),
    ]
